services:
  - name: django-app
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --preload"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productdb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

  - name: celery-worker
    type: worker
    env: python
    buildCommand: "./build.sh"
    startCommand: "celery -A config worker --pool=solo -l info"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: productdb
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true

  - name: redis
    type: redis
    plan: free
    ipAllowList: []

databases:
  - name: productdb
    plan: free
    databaseName: productdb
    user: productuser
